# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 713018f8d8e34bab2807764b287bbaaaaa424a6ecf790fc3962ecf8d77f7dfb3c96a8403eacbd8572139e6b5308016e5ada715654d80bc72298b21f44bf005b7

test:
  secret_key_base: 940d45b76d3643469aaab9fffc59371367c8d7ad833e43a62e951cb8bf844dc858b673718296c7df0397a345d395de994b6c5797de62562bd2e7f6d6ed2d8908

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
